include:
  - project: 'kmohrf/gitlab-recipes'
    ref: main
    file: '/templates/main.gitlab-ci.yml'

variables:
  DEBBUILD_DEFAULT: $DEBBUILD_PY_BULLSEYE

lint::python-types:
  image: node:lts-buster-slim
  stage: test
  tags:
    - fast-io
  script:
    - apt update && apt install -y make python3-pip wget
    - pip3 install ./ uwsgidecorators sentry_sdk
    - npm install -g pyright
    - make lint-python-pyright

test::python:
  before_script:
    - echo "gitlab.localhost" >/etc/hosts
  parallel:
    matrix:
      - IMAGE:
        - $DEBBUILD_PY_BULLSEYE
