image: git-registry.hack-hro.de:443/kmohrf/pipedput/build:buster

stages:
  - test
  - build
  - deploy

.run_tests: &run_tests
  stage: test
  variables:
    TOX_SKIP_ENV: lint
  script:
    - tox -v

lint:
  <<: *run_tests
  variables:
    TOX_SKIP_ENV: test-*

lint::types:
  image: node:lts-buster-slim
  stage: test
  script:
    - apt update && apt install -y make python3-pip wget
    - pip3 install ./ uwsgidecorators sentry_sdk
    - npm install -g pyright
    - make lint-python-pyright

test::python37:
  <<: *run_tests

build::deb-package:
  stage: build
  variables:
    PYBUILD_DISABLE: test
  script:
    - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage -sa --no-sign" DISABLE_PYTHON_TESTS=1
  artifacts:
    paths:
      - build/debian
    expire_in: 1w
