variables:
  TOX_VERSION: ">=3.21,<4.0"
  LANG: C.UTF-8

default:
  image: git-registry.hack-hro.de:443/kmohrf/pipedput/build:buster

stages:
  - test
  - build
  - deploy

.run_tox: &run_tox
  stage: test
  variables:
    TOX_SKIP_ENV: lint
  before_script:
    - pip3 install "tox$TOX_VERSION"
  script:
    - PATH=/usr/local/bin:$PATH tox -v

lint:
  <<: *run_tox
  variables:
    TOX_SKIP_ENV: test-*

lint::types:
  image: node:lts-buster-slim
  stage: test
  script:
    - apt update && apt install -y make python3-pip wget
    - pip3 install ./ uwsgidecorators sentry_sdk
    - npm install -g pyright
    - make lint-python-pyright

test::python37:
  <<: *run_tox

build::deb-package:
  stage: build
  variables:
    PYBUILD_DISABLE: test
  script:
    - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage -sa --no-sign" DISABLE_PYTHON_TESTS=1
  artifacts:
    paths:
      - build/debian
    expire_in: 1w
