image: debian:stretch

before_script:
    - apt update -qqy
    - apt install -qqy debhelper dh-exec dh-python python3-all python3-flake8 python3-flask python3-setuptools python3-werkzeug wget

make_test:
    stage: test
    script:
        - make test

make_deb_package:
    stage: deploy
    only:
        - tags
        - triggers
        - schedules
    script:
        - make dist-deb DEBIAN_BUILDPACKAGE_COMMAND="dpkg-buildpackage --no-sign"
    artifacts:
        paths:
            - build/debian
        expire_in: 1w
